---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Chatbot'

Parameters: 
  ConfigurationNameParam: 
    Type: String
  SlackChannelIdParam: 
    Type: String
  SlackWorkspaceIdParam:
    Type: String
  SnsTopicArnsParam:
    Type: CommaDelimitedList
  IamRoleArnArnParam:
    Type: String
  LoggingLevelParam:
    Type: String
    Description: Specifies the logging level for this configuration. This property affects the log entries pushed to Amazon CloudWatch Logs. Logging levels include ERROR, INFO, or NONE.
    AllowedValues:
      - ERROR
      - INFO
      - NONE

Resources:
  Chatbot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties: 
      ConfigurationName: 
        !Ref ConfigurationNameParam
      IamRoleArn: 
        !Ref IamRoleArnArnParam
      SlackChannelId: 
        !Ref SlackChannelIdParam
      SlackWorkspaceId: 
        !Ref SlackWorkspaceIdParam
      SnsTopicArns: 
        !Ref SnsTopicArnsParam
      LoggingLevel:
        !Ref LoggingLevelParam

Outputs:
  ConfigurationArn:
    Description: The ARN of the Chatbot Slack configuration
    Value: !Ref Chatbot
